version: "3"

services:
  db:
    image: mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    ports:
      - 3305:3306
    
     MYSQL_ROOT_PASSWORD: root
  app:
    container_name: appapi
    volumes:
      - .:/home
    tty: true
    links:
      - "db"
    image: pythonapi
    command: 'python3 /home/test.py'
ex